### ISSUE TITLE
Claim codes work sometimes, other times they don't!

### ISSUE THREAD

**Issue by knightsamar** [rapidpro/android-channel#1]
On Samsung Duos phone with Android 4.2.2, using the RapidPro app v 1.6.2 from the Google Play Store, with **Advanced Settings activated** against a RapidPro instance running on a server accessible from the internet at an IP Address, at the port 8000, the claim code sometimes works and the mobile is properly registered as well as a success page is displayed. Other times, this Android app simply shows "_Registering_" and then generates a new claim code even though the web page shows a success message.

I don't know how to debug this,  so let me know what more information is needed and from where could I get it.

**Comment by ewheeler** [comment]
Try checking if both devices (server and android) have their clocks set correctly. The codes are time-based, so if the clocks are too far apart the codes will not match properly.

**Comment by knightsamar** [comment]
So, does this also mean that both should be in the same time zone ?

**Comment by nicpottier** [comment]
The timestamps are UTC, so no, they do not need to be in the same timezone, but they do both need to be correct.

To debug this I would add some prints to:
   https://github.com/rapidpro/rapidpro/blob/master/temba/channels/views.py#L216

That's the view that handles syncs and such.

**Comment by irak2010** [comment]
The problem is you got a difference of time (between your android phone and your computer) > to 15 min.  So after i noticed i had a difference of 4 hours, i changed the code to accept the difference of 5 hours.
The code to change is this one https://github.com/rapidpro/rapidpro/blob/master/temba/channels/views.py#L216 (line 239)
original code:
check that the request isn't too old (15 mins)
    now = time.time()
    if abs(now - int(request_time)) > 60 \* 15:
       return HttpResponse(status=401, content='{ "error_id": 3, "error": "Old Request", "cmds":[] }')

changed code:
    now = time.time()
    if abs(now - int(request_time)) > 60 \* 300:
        print "DIFF:%s" % (now - int(request_time))
        print "NOW: %s" % datetime.fromtimestamp(int(now)).strftime('%Y-%m-%d %H:%M:%S')
        print "REQUEST TIME %s" % datetime.fromtimestamp(int(request_time)).strftime('%Y-%m-%d %H:%M:%S')
        print "DIFFERENT TIME (old request)"
        return HttpResponse(status=401, content='{ "error_id": 3, "error": "Old Request", "cmds":[] }')

**Comment by nicpottier** [comment]
This is by design to prevent replay attacks. There's no valid scenario where your phone should be more than 15 minutes off from your server, it will cause headaches down the line.
