### ISSUE TITLE
Routing message when using two channels

### ISSUE THREAD

**Issue by irak2010** [rapidpro/android-channel#2]
Hi, i'm using two channels, the first for x operator and the second for y operator. How can i route outgoing messages to the first or second channel depending on the phone number.

Thanks for your help.

**Comment by ericnewcomer** [comment]
Contacts have affinity for the last channel the messaged over. If they don't have any affinity establish, the platform will decide which channel to use based on the prefix of the number (whichever prefix has the most overlap). In the UI, you can't override this behavior. However, you can select which channel to use via the API.

**Comment by irak2010** [comment]
Thank you for your answer.
