### ISSUE TITLE
Firebase Cloud Messaging setup required to run app -- but is it used?

### ISSUE THREAD

**Issue by jpage4500** [rapidpro/android-channel#20]
Hi,

I was able to sync and run this project but noticed that I had to first create a new app in Google's Firebase console so I could setup Cloud Messaging and download a google-services.json file (the app won't build w/out it). I didn't see anything about that documented - figured maybe it was added later on?

Anyway, now that my client is getting an FCM ID and sending it over to the server -- what does the server do with it? I've yet to see a push message come in on the client.

I would think that the server also needs to be configured with the corresponding Firebase 'server key' so maybe that needs to be setup first. If so, how can I do that?

I did notice I could add a new channel - Firebase Messaging - from the settings/admin page. I did this and added the server key there - but still didn't see any messages come in.

It does seem like a great idea to send out a push message to attached clients when there's a need to sync -- for example right after entering the "Claim Code" one could be sent and the client would immediately register/login.

thanks,
joe

**Comment by nicpottier** [comment]
Hi Joe. Hrmm, ya, it looks like we are a bit behind on documentation, people running their own relayers isn't a super common case so you are on a lightly trodden path. If you could contribute some notes on your process we'd love to fold those in.

So the Firebase channel type is a totally different thing, that's a really niche use case where people are using RapidPro with in-app messaging so have their own app that handles incoming and outgoing messages with a user, etc..

The piece you are looking for is `FCM_API_KEY` in your `settings.py` in RapidPro. That's what is used to trigger a sync of the Android client:
  https://github.com/rapidpro/rapidpro/blob/master/temba/channels/models.py#L1151

With that set you should be able to get the server notifying the client to sync, which yes, it does after being claimed or when a new message needs to be sent etc.. (though we are at the whim of Google and its Firebase logic as to whether the client will actually be woken up for those events)
